---

matrix:
  include:
    - os: osx
      osx_image: xcode11
      language: generic

before_install:
  - brew update

install:
  - brew upgrade ansible
  - brew install ansible-lint
  - sudo pip3 install ansible-review
  - sudo pip3 install yamllint
  - ansible-galaxy install -r roles/requirements.yml

before_script:
  - yamllint --version
  - ansible-lint --version
  - ansible-review --version
  - ansible --version

script:
  - yamllint .
  - git ls-files | grep yml | xargs ansible-lint --exclude=/Users/travis/.ansible/roles
  - git ls-files | grep yml | grep -v vars | xargs ansible-review -q
  - ls -1 *.yml | xargs ansible-playbook --syntax-check --list-tasks -i 127.0.0.1,
  - ls -1 *.yml | xargs ansible-playbook --check --diff -i 127.0.0.1, -c local
