---

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

before_install:
  - brew update

install:
  - brew install ansible
  - brew install ansible-lint
  - pip install ansible-review
  - pip install yamllint
  - sudo gem install mdl

before_script:
  - yamllint --version
  - ansible-lint --version
  - ansible-review --version
  - ansible --version
  - mdl --version

script:
  - yamllint .
  - ansible-lint -v deekayen-macbook.yml
  - ansible-lint -v dnorman-macbook.yml
  - git ls-files | grep yml | grep -v vars | xargs ansible-review -q
  - ansible-playbook --check --diff -i localhost, -c local deekayen-macbook.yml
  - ansible-playbook --check --diff -i localhost, -c local dnorman-macbook.yml
  - mdl -gv ./
