---

os: osx
osx_image: xcode12
language: generic

env:
  jobs:
    - PLAYBOOK: deekayen-macbook
    - PLAYBOOK: dnorman-macbook

install:
  - brew unlink python@2
  - brew install ansible-lint
  - brew install yamllint
  - ansible-galaxy install -r roles/requirements.yml

before_script:
  - yamllint --version
  - ansible-lint --version
  - ansible --version

script:
  - yamllint .
  - ansible-lint --exclude=/Users/travis/.ansible/roles .
  - ansible-playbook --syntax-check --list-tasks -i 127.0.0.1, $PLAYBOOK.yml
  - ansible-playbook --diff -i 127.0.0.1, -c local --skip-tags no_ci $PLAYBOOK.yml
