matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

jobs:
  include:
    - stage: yamllint
      install:
        - pip install yamllint
      before_script:
        - yamllint --version
      script:
        - yamllint .

    - stage: ansible-lint
      before_install:
        - brew update
      install:
        - brew install ansible-lint
      before_script:
        - ansible-lint --version
      script:
        - ansible-lint -v deekayen-macbook.yml
        - ansible-lint -v dnorman-macbook.yml

    - stage: ansible-review
      install:
        - pip install ansible-review
      before_script:
        - ansible-review --version
      script:
        - git ls-files | grep yml | grep -v vars | xargs ansible-review -q

    - stage: ansible-playbook
      before_install:
        - brew update
      install:
        - brew install ansible
      before_script:
        - ansible --version
      script:
        - ansible-playbook --check --diff -i localhost, -c local deekayen-macbook.yml
        - ansible-playbook --check --diff -i localhost, -c local dnorman-macbook.yml

    - stage: mdl
      install:
        - sudo gem install mdl
      before_script:
        - mdl --version
      script:
        - mdl -gv ./
