language: python
os: osx
matrix:
  include:
    - osx_image: xcode8.3
    - osx_image: xcode8
before_install:
  - brew update
  - brew install ansible
script: ansible-playbook --diff -i localhost, -c local deekayen-macbook.yml
