---

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

before_install:
  - brew update

install:
  - brew upgrade gnupg
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  - rvm get head
  - wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
  - brew install ansible
  - brew install ansible-lint
  - sudo python /tmp/get-pip.py
  - sudo pip install ansible-review
  - sudo pip install yamllint
  - ansible-galaxy install -r roles/requirements.yml

before_script:
  - yamllint --version
  - ansible-lint --version
  - ansible-review --version
  - ansible --version

script:
  - yamllint .
  - ansible-lint -v deekayen-macbook.yml
  - ansible-lint -v dnorman-macbook.yml
  - git ls-files | grep yml | grep -v vars | xargs ansible-review -q
  - ansible-playbook --check --diff -i localhost, -c local deekayen-macbook.yml
  - ansible-playbook --check --diff -i localhost, -c local dnorman-macbook.yml
