---

os: osx
osx_image: xcode11.6
language: generic

env:
  jobs:
    - PLAYBOOK: deekayen-macbook
    - PLAYBOOK: dnorman-macbook

before_install:
  - brew update

install:
  - brew unlink python@2
  - brew upgrade ansible python
  - brew install ansible-lint
  - sudo pip3 install yamllint
  - ansible-galaxy install -r roles/requirements.yml

before_script:
  - yamllint --version
  - ansible-lint --version
  - ansible --version

script:
  - yamllint .
  - git ls-files | grep yml | xargs ansible-lint --exclude=/Users/travis/.ansible/roles
  - ansible-playbook --syntax-check --list-tasks -i 127.0.0.1, $PLAYBOOK.yml
  - ansible-playbook --diff -i 127.0.0.1, -c local --skip-tags no_ci $PLAYBOOK.yml
