matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic
before_install:
  - brew update
  - brew install ansible
script: ansible-playbook --diff -i localhost, -c local deekayen-macbook.yml
