---
- hosts: localhost
  connection: local

  vars:
    homebrew_installed_packages:
      - ansible
      - ansible-lint
      - autoconf
      - awscli
      - bash
      - dos2unix
      - ffmpeg
      - git
      - git-lfs
      - gnupg
      - gnupg2
      - gpg-agent
      - htop-osx
      - hugo
      - jp2a
      - libav
      - libdvdcss
      - mcrypt
      - md5sha1sum
      - mosh
      - nmap
      - openssh
      - openssl
      - pandoc
      - pngout
      - pre-commit
      - pwgen
      - ruby
      - unix2dos
      - unrar
      - wget
      - xz
      - youtube-dl
    homebrew_cask_apps:
      - 1password
      - alfred
      - amazon-drive
      - amazon-music
      - android-file-transfer
      - applepi-baker
      - atom
      - authy-desktop
      - bartender
      - blueharvest
      - caffeine
      - calibre
      - carbon-copy-cloner
      - dash
      - divvy
      - dropbox
      - expandrive
      - firefox
      - font-anonymous-pro
      - font-bitstream-vera
      - font-hack
      - font-lato
      - font-source-code-pro
      - font-source-sans-pro
      - font-source-serif-pro
      - gimp
      - google-drive
      - gpgtools
      - handbrake
      - horndis
      - imageoptim
      - istat-menus
      - iterm2
      - java
      - kaleidoscope
      - keka
      - kindle
      - kindlegen
      - lastpass
      - libreoffice
      - monodraw
      - multipass
      - protonmail-bridge
      - protonvpn
      - ripit
      - signal
      - skitch
      - slack
      - smartgit
      - sparkleshare
      - thunderbird
      - torbrowser
      - transmission
      - ukelele
      - viscosity
      - vlc
      - yubico-authenticator

  pre_tasks:
    - homebrew_tap:
        name: "{{ item }}"
      loop:
        - homebrew/cask-cask
        - homebrew/cask-fonts
        - jonof/kenutils

  roles:
    - finder
    - macos
    - safari
    - screensaver
    - geerlingguy.homebrew
    - smartgit
    - bin
    - google-chrome
    - gpgtools
    - motd
    - viscosityvpn
