---
- hosts: localhost
  connection: local

  vars:
    homebrew_installed_packages:
      - aescrypt
      - ansible
      - ansible-lint
      - autoconf
      - automake
      - aws-okta
      - awscli
      - bash
      - cmake
      - cowsay
      - docker
      - docker-machine
      - dos2unix
      - ffmpeg
      - gcc
      - git
      - git-lfs
      - gnupg
      - gnupg2
      - gpg-agent
      - groovy
      - htop-osx
      - jp2a
      - kubernetes-cli
      - mcrypt
      - md5sha1sum
      - molecule
      - mosh
      - nmap
      - openssh
      - openssl
      - openssl@1.1
      - osquery
      - pngout
      - pre-commit
      - pwgen
      - python
      - python@2
      - ruby
      - sqlite
      - summon
      - terraform
      - unix2dos
      - unrar
      - wget
      - yamllint
      - youtube-dl
    homebrew_taps:
      - caskroom/cask
      - caskroom/fonts
      - jonof/kenutils
    homebrew_cask_apps:
      - 1password
      - alfred
      - android-file-transfer
      - atom
      - bartender
      - blueharvest
      - caffeine
      - dash
      - divvy
      - eclipse-ide
      - filezilla
      - firefox
      - font-anonymous-pro
      - font-bitstream-vera
      - font-hack
      - font-lato
      - font-source-code-pro
      - font-source-sans-pro
      - font-source-serif-pro
      - gimp
      - horndis
      - imageoptim
      - istat-menus
      - iterm2
      - java
      - karabiner-elements
      - keepassx
      - keka
      - kitematic
      - lastpass
      - libreoffice
      - monodraw
      - multipass
      - mute-me
      - muzzle
      - pgadmin4
      - postman
      - send-to-kindle
      - skitch
      - smartgit
      - smartsynchronize
      - sourcetree
      - sublime-merge
      - sublime-text
      - textual
      - vmware-fusion
      - homebrew/cask-drivers/yubico-authenticator

  roles:
    - finder
    - macos
    - safari
    - screensaver
    - geerlingguy.homebrew
    - role: smartgit
      smartgit_user_home: /Users/dnorman
    - bin
    - google-chrome
    - motd
    - hitrust
    - ansible
    - cowsay

# safari-fido-u2f
# https://github.com/Safari-FIDO-U2F/Safari-FIDO-U2F
