---
- hosts: localhost
  connection: local

  vars:
    homebrew_installed_packages:
      - aescrypt
      - ansible
      - ansible-lint
      - autoconf
      - automake
      - awscli
      - bash
      - cmake
      - cowsay
      - dos2unix
      - ffmpeg
      - gcc
      - git
      - git-lfs
      - gnupg
      - gnupg2
      - htop-osx
      - jp2a
      - kubernetes-cli
      - mcrypt
      - md5sha1sum
      - molecule
      - mosh
      - nmap
      - openssh
      - openssl
      - openssl@1.1
      - osquery
      - pngout
      - pre-commit
      - pwgen
      - ruby
      - saml2aws
      - summon
      - unix2dos
      - unrar
      - wget
      - yamllint
    homebrew_taps:
      - cyberark/tools
      - homebrew/core
      - homebrew/cask-fonts
      - jonof/kenutils
      - versent/homebrew-taps
    homebrew_cask_apps:
      - 1password
      - alfred
      - apache-directory-studio
      - atom
      - bartender
      - blueharvest
      - caffeine
      - dash
      - divvy
      - firefox
      - font-anonymous-pro
      - font-bitstream-vera
      - font-hack
      - font-lato
      - font-mononoki
      - font-mononoki-nerd-font
      - font-mononoki-nerd-font-mono
      - font-source-code-pro
      - font-source-sans-pro
      - font-source-serif-pro
      - gimp
      - istat-menus
      - iterm2
      - java
      - kap
      - karabiner-elements
      - keepassx
      - keka
      - libreoffice
      - little-snitch
      - monodraw
      - muzzle
      - pgadmin4
      - powershell
      - send-to-kindle
      - skitch
      - smartgit
      - smartsynchronize
      - soundflower
      - soundflowerbed
      - sparkleshare
      - sublime-text
      - vmware-fusion
      - homebrew/cask-drivers/yubico-authenticator

  roles:
    - finder
    - macos
    - safari
    - screensaver
    - geerlingguy.homebrew
    - role: smartgit
      smartgit_user_home: /Users/dnorman
    - bin
    - motd
    - hitrust
    - ansible
    - cowsay
