---
- hosts: localhost
  connection: local

  vars:
    homebrew_installed_packages:
      - ansible
      - ansible-lint
      - ant
      - autoconf
      - awscli
      - bash
      - cowsay
      - dos2unix
      - ffmpeg
      - git
      - git-lfs
      - gnupg
      - gnupg2
      - gpg-agent
      - htop-osx
      - jp2a
      - krb5
      - maven
      - mcrypt
      - md5sha1sum
      - mosh
      - nmap
      - openssh
      - openssl
      - openssl@1.1
      - osquery
      - pngout
      - pre-commit
      - pwgen
      - unix2dos
      - unrar
      - wget
    homebrew_taps:
      - caskroom/cask
      - caskroom/fonts
      - jonof/kenutils
    homebrew_cask_apps:
      - 1password
      - alfred
      - android-file-transfer
      - atom
      - bartender
      - blueharvest
      - caffeine
      - dash
      - divvy
      - eclipse-ide
      - expandrive
      - filezilla
      - firefox
      - font-anonymous-pro
      - font-bitstream-vera
      - font-hack
      - font-lato
      - font-source-code-pro
      - font-source-sans-pro
      - font-source-serif-pro
      - gimp
      - gpgtools
      - horndis
      - imageoptim
      - istat-menus
      - iterm2
      - java
      - keepassx
      - lastpass
      - muzzle
      - rescuetime
      - skitch
      - smartgit
      - sourcetree
    homebrew_upgrade_all_packages: yes

  roles:
    - finder
    - macos
    - safari
    - screensaver
    - geerlingguy.homebrew
    - role: smartgit
      smartgit_user_home: /Users/dnorman
    - bin
    - google-chrome
    - motd
    - hitrust
