---

- name: Install git and git-lfs.
  homebrew:
    name:
      - git
      - git-lfs
    state: present

- name: Install SmartGit.
  homebrew_cask:
    name: smartgit
    state: present

# https://groups.google.com/forum/#!topic/smartgit/PXaIRQJS_HU
# https://www.syntevo.com/doc/display/SG071/VM+options#VMoptions-ExtendedPATH
- name: "Create folder for smartgit.vmoptions."
  file:
    path: "{{ smartgit_user_home }}/Library/Preferences/SmartGit"
    state: directory
  tags:
    - no_ci

# Touch alone wasn't enough to create the path and file, even though the docs suggest it would.
- name: "Create a smartgit.vmoptions file."
  file:
    path: "{{ smartgit_user_home }}/Library/Preferences/SmartGit/smartgit.vmoptions"
    state: touch
  tags:
    - no_ci

- name: "Add git-lfs to the smartgit.vmoptions path."
  lineinfile:
    path: "{{ smartgit_user_home }}/Library/Preferences/SmartGit/smartgit.vmoptions"
    line: "path={{ smartgit_path }}"
  when: not ansible_check_mode
  tags:
    - no_ci
