---

- name: Enable automatic software update checks.
  osx_defaults: domain=com.troupe.gitter.mac.Gitter key=SUEnableAutomaticChecks type=bool value=true state=present

- name: Enable automatic software update installs.
  osx_defaults: domain=com.troupe.gitter.mac.Gitter key=SUAutomaticallyUpdate type=bool value=true state=present

- name: Automatically launch on startup.
  osx_defaults: domain=com.troupe.gitter.mac.Gitter key=LaunchOnStartup type=bool value=true state=present
