---

- name: Configure homebrew taps.
  homebrew_tap:
    tap: "{{ item.tap }}"
    url: "{{ item.url }}"
    state: present
  with_items:
  - "{{ homebrew_taps }}"

- name: Install homebrew packages.
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ homebrew_packages }}"
  register: homebrew_result
  failed_when:
    - homebrew_result.failed is set
    - homebrew_result.failed
    - homebrew_result.msg is set
    - not 'nothing to install' in homebrew_result.msg

- name: Recklessly upgrade homebrew packages.
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install cask apps.
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ homebrew_cask_apps }}"
