---

- name: Require password screensaver when waking from screensaver.
  osx_defaults: domain=com.apple.screensaver key=askForPassword type=int value=1 state=present

- name: Set screensaver password prompt to 0 second delay.
  osx_defaults: domain=com.apple.screensaver key=askForPasswordDelay type=float value=0 state=present

- name: Show the clock on the screensaver.
  osx_defaults: domain=com.apple.screensaver host=currentHost key=showClock type=int value=1 state=present
