---

name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "30 1 * * 5"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install test dependencies.
        run: sudo apt install ansible-lint

      - name: Lint yamllint.
        run: yamllint -f github -v --no-warnings .

      - name: Lint ansible.
        run: ansible-lint

# https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-software
  install:
    name: Playbook
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
        playbook:
          - deekayen-macbook
          - dnorman-macbook

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install ansible-lint.
        run: brew install ansible

      - name: Install galaxy dependencies.
        run: ansible-galaxy install -r roles/requirements.yml

      - name: Check syntax.
        run: ansible-playbook --syntax-check --list-tasks -i 127.0.0.1, ${{ matrix.playbook }}.yml

      - name: Run playbook.
        run: ansible-playbook --diff -i 127.0.0.1, -c local --skip-tags no_ci ${{ matrix.playbook }}.yml
